// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: game.proto

package dotscordonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cell int32

const (
	Cell_CELL_EMPTY         Cell = 0
	Cell_CELL_PLAYER_0      Cell = 1
	Cell_CELL_PLAYER_1      Cell = 2
	Cell_CELL_DEAD_EMPTY    Cell = 3
	Cell_CELL_DEAD_PLAYER_0 Cell = 4
	Cell_CELL_DEAD_PLAYER_1 Cell = 5
)

// Enum value maps for Cell.
var (
	Cell_name = map[int32]string{
		0: "CELL_EMPTY",
		1: "CELL_PLAYER_0",
		2: "CELL_PLAYER_1",
		3: "CELL_DEAD_EMPTY",
		4: "CELL_DEAD_PLAYER_0",
		5: "CELL_DEAD_PLAYER_1",
	}
	Cell_value = map[string]int32{
		"CELL_EMPTY":         0,
		"CELL_PLAYER_0":      1,
		"CELL_PLAYER_1":      2,
		"CELL_DEAD_EMPTY":    3,
		"CELL_DEAD_PLAYER_0": 4,
		"CELL_DEAD_PLAYER_1": 5,
	}
)

func (x Cell) Enum() *Cell {
	p := new(Cell)
	*p = x
	return p
}

func (x Cell) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cell) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[0].Descriptor()
}

func (Cell) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[0]
}

func (x Cell) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cell.Descriptor instead.
func (Cell) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

type TerminationReason int32

const (
	TerminationReason_TERMINATION_REASON_UNSPECIFIED TerminationReason = 0
	TerminationReason_TERMINATION_REASON_BOARD_FULL  TerminationReason = 1
	TerminationReason_TERMINATION_REASON_TURN_LIMIT  TerminationReason = 2
)

// Enum value maps for TerminationReason.
var (
	TerminationReason_name = map[int32]string{
		0: "TERMINATION_REASON_UNSPECIFIED",
		1: "TERMINATION_REASON_BOARD_FULL",
		2: "TERMINATION_REASON_TURN_LIMIT",
	}
	TerminationReason_value = map[string]int32{
		"TERMINATION_REASON_UNSPECIFIED": 0,
		"TERMINATION_REASON_BOARD_FULL":  1,
		"TERMINATION_REASON_TURN_LIMIT":  2,
	}
)

func (x TerminationReason) Enum() *TerminationReason {
	p := new(TerminationReason)
	*p = x
	return p
}

func (x TerminationReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminationReason) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[1].Descriptor()
}

func (TerminationReason) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[1]
}

func (x TerminationReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerminationReason.Descriptor instead.
func (TerminationReason) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

type CreateGameRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Rows    uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Columns uint32                 `protobuf:"varint,2,opt,name=columns,proto3" json:"columns,omitempty"`
	// Zero means that the game ends only when the board is full.
	MaxTurns      uint32 `protobuf:"varint,3,opt,name=max_turns,json=maxTurns,proto3" json:"max_turns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *CreateGameRequest) GetColumns() uint32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *CreateGameRequest) GetMaxTurns() uint32 {
	if x != nil {
		return x.MaxTurns
	}
	return 0
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *GameState             `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameResponse) GetGame() *GameState {
	if x != nil {
		return x.Game
	}
	return nil
}

type GetGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameRequest) Reset() {
	*x = GetGameRequest{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameRequest) ProtoMessage() {}

func (x *GetGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameRequest.ProtoReflect.Descriptor instead.
func (*GetGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *GetGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GetGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *GameState             `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameResponse) Reset() {
	*x = GetGameResponse{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameResponse) ProtoMessage() {}

func (x *GetGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameResponse.ProtoReflect.Descriptor instead.
func (*GetGameResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameResponse) GetGame() *GameState {
	if x != nil {
		return x.Game
	}
	return nil
}

type MakeMoveRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	GameId string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	// Must equal GameState.turn. This prevents a retried or concurrent request
	// from applying an action to a different observation.
	ExpectedTurn  uint32      `protobuf:"varint,2,opt,name=expected_turn,json=expectedTurn,proto3" json:"expected_turn,omitempty"`
	Position      *Coordinate `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveRequest) Reset() {
	*x = MakeMoveRequest{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveRequest) ProtoMessage() {}

func (x *MakeMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveRequest.ProtoReflect.Descriptor instead.
func (*MakeMoveRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *MakeMoveRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MakeMoveRequest) GetExpectedTurn() uint32 {
	if x != nil {
		return x.ExpectedTurn
	}
	return 0
}

func (x *MakeMoveRequest) GetPosition() *Coordinate {
	if x != nil {
		return x.Position
	}
	return nil
}

type MakeMoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *GameState             `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Result        *MoveResult            `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveResponse) Reset() {
	*x = MakeMoveResponse{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveResponse) ProtoMessage() {}

func (x *MakeMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveResponse.ProtoReflect.Descriptor instead.
func (*MakeMoveResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *MakeMoveResponse) GetGame() *GameState {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *MakeMoveResponse) GetResult() *MoveResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ResetGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetGameRequest) Reset() {
	*x = ResetGameRequest{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetGameRequest) ProtoMessage() {}

func (x *ResetGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetGameRequest.ProtoReflect.Descriptor instead.
func (*ResetGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *ResetGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type ResetGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *GameState             `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetGameResponse) Reset() {
	*x = ResetGameResponse{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetGameResponse) ProtoMessage() {}

func (x *ResetGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetGameResponse.ProtoReflect.Descriptor instead.
func (*ResetGameResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *ResetGameResponse) GetGame() *GameState {
	if x != nil {
		return x.Game
	}
	return nil
}

type DeleteGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameRequest) Reset() {
	*x = DeleteGameRequest{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameRequest) ProtoMessage() {}

func (x *DeleteGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameRequest.ProtoReflect.Descriptor instead.
func (*DeleteGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type DeleteGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameResponse) Reset() {
	*x = DeleteGameResponse{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameResponse) ProtoMessage() {}

func (x *DeleteGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameResponse.ProtoReflect.Descriptor instead.
func (*DeleteGameResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

type GameState struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	GameId string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Board  *Board                 `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	// Always contains [player_0_score, player_1_score].
	Scores        []uint32 `protobuf:"varint,3,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	CurrentPlayer uint32   `protobuf:"varint,4,opt,name=current_player,json=currentPlayer,proto3" json:"current_player,omitempty"`
	// Number of successfully applied moves. Player 0 acts on turn zero.
	Turn              uint32            `protobuf:"varint,5,opt,name=turn,proto3" json:"turn,omitempty"`
	Terminal          bool              `protobuf:"varint,6,opt,name=terminal,proto3" json:"terminal,omitempty"`
	TerminationReason TerminationReason `protobuf:"varint,7,opt,name=termination_reason,json=terminationReason,proto3,enum=dotscordon.v1.TerminationReason" json:"termination_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *GameState) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameState) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *GameState) GetScores() []uint32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *GameState) GetCurrentPlayer() uint32 {
	if x != nil {
		return x.CurrentPlayer
	}
	return 0
}

func (x *GameState) GetTurn() uint32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *GameState) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *GameState) GetTerminationReason() TerminationReason {
	if x != nil {
		return x.TerminationReason
	}
	return TerminationReason_TERMINATION_REASON_UNSPECIFIED
}

type Board struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Rows    uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Columns uint32                 `protobuf:"varint,2,opt,name=columns,proto3" json:"columns,omitempty"`
	// Row-major cell values. Every byte is one of the Cell enum values below.
	// This compact representation can be read directly as a uint8 tensor.
	Cells         []byte `protobuf:"bytes,3,opt,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

func (x *Board) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Board) GetColumns() uint32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *Board) GetCells() []byte {
	if x != nil {
		return x.Cells
	}
	return nil
}

type MoveResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        uint32                 `protobuf:"varint,1,opt,name=player,proto3" json:"player,omitempty"`
	ScoredPoints  uint32                 `protobuf:"varint,2,opt,name=scored_points,json=scoredPoints,proto3" json:"scored_points,omitempty"`
	KilledCells   []*Coordinate          `protobuf:"bytes,3,rep,name=killed_cells,json=killedCells,proto3" json:"killed_cells,omitempty"`
	Cordons       []*Cordon              `protobuf:"bytes,4,rep,name=cordons,proto3" json:"cordons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResult) Reset() {
	*x = MoveResult{}
	mi := &file_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResult) ProtoMessage() {}

func (x *MoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResult.ProtoReflect.Descriptor instead.
func (*MoveResult) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{12}
}

func (x *MoveResult) GetPlayer() uint32 {
	if x != nil {
		return x.Player
	}
	return 0
}

func (x *MoveResult) GetScoredPoints() uint32 {
	if x != nil {
		return x.ScoredPoints
	}
	return 0
}

func (x *MoveResult) GetKilledCells() []*Coordinate {
	if x != nil {
		return x.KilledCells
	}
	return nil
}

func (x *MoveResult) GetCordons() []*Cordon {
	if x != nil {
		return x.Cordons
	}
	return nil
}

type Cordon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Coordinate          `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cordon) Reset() {
	*x = Cordon{}
	mi := &file_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cordon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cordon) ProtoMessage() {}

func (x *Cordon) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cordon.ProtoReflect.Descriptor instead.
func (*Cordon) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{13}
}

func (x *Cordon) GetPositions() []*Coordinate {
	if x != nil {
		return x.Positions
	}
	return nil
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           uint32                 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column        uint32                 `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{14}
}

func (x *Coordinate) GetRow() uint32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Coordinate) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\rdotscordon.v1\"^\n" +
	"\x11CreateGameRequest\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x18\n" +
	"\acolumns\x18\x02 \x01(\rR\acolumns\x12\x1b\n" +
	"\tmax_turns\x18\x03 \x01(\rR\bmaxTurns\"B\n" +
	"\x12CreateGameResponse\x12,\n" +
	"\x04game\x18\x01 \x01(\v2\x18.dotscordon.v1.GameStateR\x04game\")\n" +
	"\x0eGetGameRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"?\n" +
	"\x0fGetGameResponse\x12,\n" +
	"\x04game\x18\x01 \x01(\v2\x18.dotscordon.v1.GameStateR\x04game\"\x86\x01\n" +
	"\x0fMakeMoveRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12#\n" +
	"\rexpected_turn\x18\x02 \x01(\rR\fexpectedTurn\x125\n" +
	"\bposition\x18\x03 \x01(\v2\x19.dotscordon.v1.CoordinateR\bposition\"s\n" +
	"\x10MakeMoveResponse\x12,\n" +
	"\x04game\x18\x01 \x01(\v2\x18.dotscordon.v1.GameStateR\x04game\x121\n" +
	"\x06result\x18\x02 \x01(\v2\x19.dotscordon.v1.MoveResultR\x06result\"+\n" +
	"\x10ResetGameRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"A\n" +
	"\x11ResetGameResponse\x12,\n" +
	"\x04game\x18\x01 \x01(\v2\x18.dotscordon.v1.GameStateR\x04game\",\n" +
	"\x11DeleteGameRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"\x14\n" +
	"\x12DeleteGameResponse\"\x90\x02\n" +
	"\tGameState\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12*\n" +
	"\x05board\x18\x02 \x01(\v2\x14.dotscordon.v1.BoardR\x05board\x12\x16\n" +
	"\x06scores\x18\x03 \x03(\rR\x06scores\x12%\n" +
	"\x0ecurrent_player\x18\x04 \x01(\rR\rcurrentPlayer\x12\x12\n" +
	"\x04turn\x18\x05 \x01(\rR\x04turn\x12\x1a\n" +
	"\bterminal\x18\x06 \x01(\bR\bterminal\x12O\n" +
	"\x12termination_reason\x18\a \x01(\x0e2 .dotscordon.v1.TerminationReasonR\x11terminationReason\"K\n" +
	"\x05Board\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x18\n" +
	"\acolumns\x18\x02 \x01(\rR\acolumns\x12\x14\n" +
	"\x05cells\x18\x03 \x01(\fR\x05cells\"\xb8\x01\n" +
	"\n" +
	"MoveResult\x12\x16\n" +
	"\x06player\x18\x01 \x01(\rR\x06player\x12#\n" +
	"\rscored_points\x18\x02 \x01(\rR\fscoredPoints\x12<\n" +
	"\fkilled_cells\x18\x03 \x03(\v2\x19.dotscordon.v1.CoordinateR\vkilledCells\x12/\n" +
	"\acordons\x18\x04 \x03(\v2\x15.dotscordon.v1.CordonR\acordons\"A\n" +
	"\x06Cordon\x127\n" +
	"\tpositions\x18\x01 \x03(\v2\x19.dotscordon.v1.CoordinateR\tpositions\"6\n" +
	"\n" +
	"Coordinate\x12\x10\n" +
	"\x03row\x18\x01 \x01(\rR\x03row\x12\x16\n" +
	"\x06column\x18\x02 \x01(\rR\x06column*\x81\x01\n" +
	"\x04Cell\x12\x0e\n" +
	"\n" +
	"CELL_EMPTY\x10\x00\x12\x11\n" +
	"\rCELL_PLAYER_0\x10\x01\x12\x11\n" +
	"\rCELL_PLAYER_1\x10\x02\x12\x13\n" +
	"\x0fCELL_DEAD_EMPTY\x10\x03\x12\x16\n" +
	"\x12CELL_DEAD_PLAYER_0\x10\x04\x12\x16\n" +
	"\x12CELL_DEAD_PLAYER_1\x10\x05*}\n" +
	"\x11TerminationReason\x12\"\n" +
	"\x1eTERMINATION_REASON_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dTERMINATION_REASON_BOARD_FULL\x10\x01\x12!\n" +
	"\x1dTERMINATION_REASON_TURN_LIMIT\x10\x022\x9a\x03\n" +
	"\vGameService\x12Q\n" +
	"\n" +
	"CreateGame\x12 .dotscordon.v1.CreateGameRequest\x1a!.dotscordon.v1.CreateGameResponse\x12H\n" +
	"\aGetGame\x12\x1d.dotscordon.v1.GetGameRequest\x1a\x1e.dotscordon.v1.GetGameResponse\x12K\n" +
	"\bMakeMove\x12\x1e.dotscordon.v1.MakeMoveRequest\x1a\x1f.dotscordon.v1.MakeMoveResponse\x12N\n" +
	"\tResetGame\x12\x1f.dotscordon.v1.ResetGameRequest\x1a .dotscordon.v1.ResetGameResponse\x12Q\n" +
	"\n" +
	"DeleteGame\x12 .dotscordon.v1.DeleteGameRequest\x1a!.dotscordon.v1.DeleteGameResponseB?Z=github.com/a-vzhik/dots-cordon/api/dotscordon/v1;dotscordonv1b\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_game_proto_goTypes = []any{
	(Cell)(0),                  // 0: dotscordon.v1.Cell
	(TerminationReason)(0),     // 1: dotscordon.v1.TerminationReason
	(*CreateGameRequest)(nil),  // 2: dotscordon.v1.CreateGameRequest
	(*CreateGameResponse)(nil), // 3: dotscordon.v1.CreateGameResponse
	(*GetGameRequest)(nil),     // 4: dotscordon.v1.GetGameRequest
	(*GetGameResponse)(nil),    // 5: dotscordon.v1.GetGameResponse
	(*MakeMoveRequest)(nil),    // 6: dotscordon.v1.MakeMoveRequest
	(*MakeMoveResponse)(nil),   // 7: dotscordon.v1.MakeMoveResponse
	(*ResetGameRequest)(nil),   // 8: dotscordon.v1.ResetGameRequest
	(*ResetGameResponse)(nil),  // 9: dotscordon.v1.ResetGameResponse
	(*DeleteGameRequest)(nil),  // 10: dotscordon.v1.DeleteGameRequest
	(*DeleteGameResponse)(nil), // 11: dotscordon.v1.DeleteGameResponse
	(*GameState)(nil),          // 12: dotscordon.v1.GameState
	(*Board)(nil),              // 13: dotscordon.v1.Board
	(*MoveResult)(nil),         // 14: dotscordon.v1.MoveResult
	(*Cordon)(nil),             // 15: dotscordon.v1.Cordon
	(*Coordinate)(nil),         // 16: dotscordon.v1.Coordinate
}
var file_game_proto_depIdxs = []int32{
	12, // 0: dotscordon.v1.CreateGameResponse.game:type_name -> dotscordon.v1.GameState
	12, // 1: dotscordon.v1.GetGameResponse.game:type_name -> dotscordon.v1.GameState
	16, // 2: dotscordon.v1.MakeMoveRequest.position:type_name -> dotscordon.v1.Coordinate
	12, // 3: dotscordon.v1.MakeMoveResponse.game:type_name -> dotscordon.v1.GameState
	14, // 4: dotscordon.v1.MakeMoveResponse.result:type_name -> dotscordon.v1.MoveResult
	12, // 5: dotscordon.v1.ResetGameResponse.game:type_name -> dotscordon.v1.GameState
	13, // 6: dotscordon.v1.GameState.board:type_name -> dotscordon.v1.Board
	1,  // 7: dotscordon.v1.GameState.termination_reason:type_name -> dotscordon.v1.TerminationReason
	16, // 8: dotscordon.v1.MoveResult.killed_cells:type_name -> dotscordon.v1.Coordinate
	15, // 9: dotscordon.v1.MoveResult.cordons:type_name -> dotscordon.v1.Cordon
	16, // 10: dotscordon.v1.Cordon.positions:type_name -> dotscordon.v1.Coordinate
	2,  // 11: dotscordon.v1.GameService.CreateGame:input_type -> dotscordon.v1.CreateGameRequest
	4,  // 12: dotscordon.v1.GameService.GetGame:input_type -> dotscordon.v1.GetGameRequest
	6,  // 13: dotscordon.v1.GameService.MakeMove:input_type -> dotscordon.v1.MakeMoveRequest
	8,  // 14: dotscordon.v1.GameService.ResetGame:input_type -> dotscordon.v1.ResetGameRequest
	10, // 15: dotscordon.v1.GameService.DeleteGame:input_type -> dotscordon.v1.DeleteGameRequest
	3,  // 16: dotscordon.v1.GameService.CreateGame:output_type -> dotscordon.v1.CreateGameResponse
	5,  // 17: dotscordon.v1.GameService.GetGame:output_type -> dotscordon.v1.GetGameResponse
	7,  // 18: dotscordon.v1.GameService.MakeMove:output_type -> dotscordon.v1.MakeMoveResponse
	9,  // 19: dotscordon.v1.GameService.ResetGame:output_type -> dotscordon.v1.ResetGameResponse
	11, // 20: dotscordon.v1.GameService.DeleteGame:output_type -> dotscordon.v1.DeleteGameResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		EnumInfos:         file_game_proto_enumTypes,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
