/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiments */
        get: operations["experiments_api_v1_experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lineage */
        get: operations["lineage_api_v1_experiments__id__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attempts */
        get: operations["attempts_api_v1_attempts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attempts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attempt */
        get: operations["attempt_api_v1_attempts__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attempts/{id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_v1_attempts__id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkpoints/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checkpoint */
        get: operations["checkpoint_api_v1_checkpoints__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkpoints/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_api_v1_checkpoints__id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluation */
        get: operations["evaluation_api_v1_evaluations__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AncestryEdge */
        AncestryEdge: {
            /** Parent Checkpoint Id */
            parent_checkpoint_id: string;
            /** Child Checkpoint Id */
            child_checkpoint_id: string;
        };
        /** AttemptCounts */
        AttemptCounts: {
            /** Checkpoints */
            checkpoints: number;
            /** Qualified Checkpoints */
            qualified_checkpoints: number;
            /** Challenge Batches */
            challenge_batches: number;
            /** Promotions */
            promotions: number;
        };
        /** AttemptDetail */
        AttemptDetail: {
            /** Id */
            id: string;
            /** Experiment Id */
            experiment_id: string;
            /** Starting Checkpoint Id */
            starting_checkpoint_id: string | null;
            /** Champion At Start Assignment Id */
            champion_at_start_assignment_id: string | null;
            /** Start Episode */
            start_episode: number;
            /** Target Episode */
            target_episode: number;
            /** Latest Episode */
            latest_episode: number;
            /**
             * Phase
             * @enum {string}
             */
            phase: "training" | "screening" | "challenging" | "finished";
            /**
             * Status
             * @enum {string}
             */
            status: "planned" | "running" | "completed" | "interrupted" | "failed" | "abandoned" | "cancelled";
            /** Outcome */
            outcome: string | null;
            /** Error */
            error: string | null;
            /** Stop Reason */
            stop_reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /**
             * Heartbeat At
             * Format: date-time
             */
            heartbeat_at: string;
            /** Last Interrupted At */
            last_interrupted_at: string | null;
            /** Last Resumed At */
            last_resumed_at: string | null;
            /** Error At */
            error_at: string | null;
            diagnostics: components["schemas"]["Diagnostics"];
            counts: components["schemas"]["AttemptCounts"];
            /** Config */
            config: {
                [key: string]: unknown;
            };
            checkpoints: components["schemas"]["Page_CheckpointSummary_"];
        };
        /** AttemptSummary */
        AttemptSummary: {
            /** Id */
            id: string;
            /** Experiment Id */
            experiment_id: string;
            /** Starting Checkpoint Id */
            starting_checkpoint_id: string | null;
            /** Champion At Start Assignment Id */
            champion_at_start_assignment_id: string | null;
            /** Start Episode */
            start_episode: number;
            /** Target Episode */
            target_episode: number;
            /** Latest Episode */
            latest_episode: number;
            /**
             * Phase
             * @enum {string}
             */
            phase: "training" | "screening" | "challenging" | "finished";
            /**
             * Status
             * @enum {string}
             */
            status: "planned" | "running" | "completed" | "interrupted" | "failed" | "abandoned" | "cancelled";
            /** Outcome */
            outcome: string | null;
            /** Error */
            error: string | null;
            /** Stop Reason */
            stop_reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /**
             * Heartbeat At
             * Format: date-time
             */
            heartbeat_at: string;
            /** Last Interrupted At */
            last_interrupted_at: string | null;
            /** Last Resumed At */
            last_resumed_at: string | null;
            /** Error At */
            error_at: string | null;
            diagnostics: components["schemas"]["Diagnostics"];
            counts: components["schemas"]["AttemptCounts"];
        };
        /** BlobMetadata */
        BlobMetadata: {
            /** Available */
            available: boolean;
            /** Sha256 */
            sha256: string | null;
            /** Byte Length */
            byte_length: number | null;
            /** Format */
            format: string | null;
            /** Format Version */
            format_version: number | null;
        };
        /** Board */
        Board: {
            /** Rows */
            rows: number;
            /** Columns */
            columns: number;
        };
        /** BranchCounts */
        BranchCounts: {
            /** Attempts */
            attempts: number;
            /** Qualified Checkpoints */
            qualified_checkpoints: number;
            /** Challenge Batches */
            challenge_batches: number;
            /** Promotions */
            promotions: number;
        };
        /** ChampionAssignment */
        ChampionAssignment: {
            /** Id */
            id: string;
            /** Experiment Id */
            experiment_id: string;
            /** Generation */
            generation: number;
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Previous Assignment Id */
            previous_assignment_id: string | null;
            /** Attempt Id */
            attempt_id: string | null;
            /** Decision Id */
            decision_id: string | null;
            /** Reason */
            reason: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CheckpointCounts */
        CheckpointCounts: {
            /** Child Checkpoints */
            child_checkpoints: number;
            /** Attempts From Checkpoint */
            attempts_from_checkpoint: number;
            /** Evaluation Batches */
            evaluation_batches: number;
            /** Decisions */
            decisions: number;
        };
        /** CheckpointDetail */
        CheckpointDetail: {
            /** Id */
            id: string;
            /** Experiment Id */
            experiment_id: string;
            /** Attempt Id */
            attempt_id: string | null;
            /** Checkpoint Blob Id */
            checkpoint_blob_id: string;
            /** Parent Checkpoint Id */
            parent_checkpoint_id: string | null;
            /** Episode */
            episode: number;
            /** Environment Steps */
            environment_steps: number;
            /** Optimization Steps */
            optimization_steps: number;
            board: components["schemas"]["Board"];
            model: components["schemas"]["ModelArchitecture"];
            /** Origin */
            origin: string;
            /** Save Sequence */
            save_sequence: number;
            /** Candidate Index */
            candidate_index: number | null;
            /** Is Periodic Save */
            is_periodic_save: boolean;
            /** Is Screening Candidate */
            is_screening_candidate: boolean;
            /** Is Best In Attempt */
            is_best_in_attempt: boolean;
            /** Is Final In Attempt */
            is_final_in_attempt: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            blob: components["schemas"]["BlobMetadata"];
            counts: components["schemas"]["CheckpointCounts"];
            /** Recent Evaluations */
            recent_evaluations: components["schemas"]["EvaluationSummary"][];
            /** Recent Decisions */
            recent_decisions: components["schemas"]["DecisionSummary"][];
            evaluations: components["schemas"]["Page_EvaluationSummary_"];
        };
        /** CheckpointNode */
        CheckpointNode: {
            /** Id */
            id: string;
            /** Experiment Id */
            experiment_id: string;
            /** Attempt Id */
            attempt_id: string | null;
            /** Checkpoint Blob Id */
            checkpoint_blob_id: string;
            /** Parent Checkpoint Id */
            parent_checkpoint_id: string | null;
            /** Episode */
            episode: number;
            /** Environment Steps */
            environment_steps: number;
            /** Optimization Steps */
            optimization_steps: number;
            board: components["schemas"]["Board"];
            model: components["schemas"]["ModelArchitecture"];
            /** Origin */
            origin: string;
            /** Save Sequence */
            save_sequence: number;
            /** Candidate Index */
            candidate_index: number | null;
            /** Is Periodic Save */
            is_periodic_save: boolean;
            /** Is Screening Candidate */
            is_screening_candidate: boolean;
            /** Is Best In Attempt */
            is_best_in_attempt: boolean;
            /** Is Final In Attempt */
            is_final_in_attempt: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            blob: components["schemas"]["BlobMetadata"];
            counts: components["schemas"]["CheckpointCounts"];
            /** Recent Evaluations */
            recent_evaluations: components["schemas"]["EvaluationSummary"][];
            /** Recent Decisions */
            recent_decisions: components["schemas"]["DecisionSummary"][];
            /** Is Boundary */
            is_boundary: boolean;
            /** Children Outside Slice */
            children_outside_slice: number;
        };
        /** CheckpointSummary */
        CheckpointSummary: {
            /** Id */
            id: string;
            /** Experiment Id */
            experiment_id: string;
            /** Attempt Id */
            attempt_id: string | null;
            /** Checkpoint Blob Id */
            checkpoint_blob_id: string;
            /** Parent Checkpoint Id */
            parent_checkpoint_id: string | null;
            /** Episode */
            episode: number;
            /** Environment Steps */
            environment_steps: number;
            /** Optimization Steps */
            optimization_steps: number;
            board: components["schemas"]["Board"];
            model: components["schemas"]["ModelArchitecture"];
            /** Origin */
            origin: string;
            /** Save Sequence */
            save_sequence: number;
            /** Candidate Index */
            candidate_index: number | null;
            /** Is Periodic Save */
            is_periodic_save: boolean;
            /** Is Screening Candidate */
            is_screening_candidate: boolean;
            /** Is Best In Attempt */
            is_best_in_attempt: boolean;
            /** Is Final In Attempt */
            is_final_in_attempt: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            blob: components["schemas"]["BlobMetadata"];
            counts: components["schemas"]["CheckpointCounts"];
            /** Recent Evaluations */
            recent_evaluations: components["schemas"]["EvaluationSummary"][];
            /** Recent Decisions */
            recent_decisions: components["schemas"]["DecisionSummary"][];
        };
        /** CurrentChampion */
        CurrentChampion: {
            assignment: components["schemas"]["ChampionAssignment"];
            checkpoint: components["schemas"]["CheckpointSummary"];
            branches?: components["schemas"]["BranchCounts"] | null;
        };
        /** Decision */
        Decision: {
            /** Id */
            id: string;
            /** Attempt Id */
            attempt_id: string;
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Stage */
            stage: string;
            /** Result */
            result: string;
            /** Reason */
            reason: string | null;
            /** Candidate Evaluation Id */
            candidate_evaluation_id: string | null;
            /** Champion Evaluation Id */
            champion_evaluation_id: string | null;
            /** Rank */
            rank: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Policy */
            policy: {
                [key: string]: unknown;
            };
        };
        /** DecisionSummary */
        DecisionSummary: {
            /** Id */
            id: string;
            /** Attempt Id */
            attempt_id: string;
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Stage */
            stage: string;
            /** Result */
            result: string;
            /** Reason */
            reason: string | null;
            /** Candidate Evaluation Id */
            candidate_evaluation_id: string | null;
            /** Champion Evaluation Id */
            champion_evaluation_id: string | null;
            /** Rank */
            rank: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Diagnostics */
        Diagnostics: {
            /** Last Activity At */
            last_activity_at: string | null;
            /** Heartbeat Age Seconds */
            heartbeat_age_seconds: number | null;
            /** Unresponsive */
            unresponsive: boolean;
            /** Unresponsive After Seconds */
            unresponsive_after_seconds: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            }[];
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** EvaluationDetail */
        EvaluationDetail: {
            /** Id */
            id: string;
            /** Experiment Id */
            experiment_id: string;
            /** Attempt Id */
            attempt_id: string | null;
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Opponent Checkpoint Id */
            opponent_checkpoint_id: string | null;
            /** Opponent Kind */
            opponent_kind: string;
            /** Purpose */
            purpose: string;
            /**
             * Status
             * @enum {string}
             */
            status: "planned" | "running" | "completed" | "interrupted" | "failed" | "abandoned" | "cancelled";
            /** Planned Suite Count */
            planned_suite_count: number;
            /** Recorded Suite Count */
            recorded_suite_count: number;
            /** Completed Suite Count */
            completed_suite_count: number;
            /** Expected Games */
            expected_games: number;
            /** Completed Games */
            completed_games: number;
            /**
             * Score Orientation
             * @constant
             */
            score_orientation: "subject";
            /** Is Complete */
            is_complete: boolean;
            /** Aggregate Is Partial */
            aggregate_is_partial: boolean;
            aggregate: components["schemas"]["Scores"] | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /**
             * Heartbeat At
             * Format: date-time
             */
            heartbeat_at: string;
            diagnostics: components["schemas"]["Diagnostics"];
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Participants */
            participants: components["schemas"]["CheckpointSummary"][];
            suites: components["schemas"]["Page_EvaluationSuite_"];
            decisions: components["schemas"]["Page_Decision_"];
        };
        /** EvaluationSuite */
        EvaluationSuite: {
            /** Id */
            id: string;
            /** Batch Id */
            batch_id: string;
            /** Suite Index */
            suite_index: number;
            /** Definition */
            definition: {
                [key: string]: unknown;
            };
            /** Suite Fingerprint */
            suite_fingerprint: string;
            /** Expected Games */
            expected_games: number;
            /** Expected Player 0 Games */
            expected_player_0_games: number;
            /** Expected Player 1 Games */
            expected_player_1_games: number;
            /**
             * Status
             * @enum {string}
             */
            status: "planned" | "running" | "completed" | "interrupted" | "failed" | "abandoned" | "cancelled";
            /** Elapsed Seconds */
            elapsed_seconds: number | null;
            /** Error */
            error: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            result: components["schemas"]["Scores"] | null;
        };
        /** EvaluationSummary */
        EvaluationSummary: {
            /** Id */
            id: string;
            /** Experiment Id */
            experiment_id: string;
            /** Attempt Id */
            attempt_id: string | null;
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Opponent Checkpoint Id */
            opponent_checkpoint_id: string | null;
            /** Opponent Kind */
            opponent_kind: string;
            /** Purpose */
            purpose: string;
            /**
             * Status
             * @enum {string}
             */
            status: "planned" | "running" | "completed" | "interrupted" | "failed" | "abandoned" | "cancelled";
            /** Planned Suite Count */
            planned_suite_count: number;
            /** Recorded Suite Count */
            recorded_suite_count: number;
            /** Completed Suite Count */
            completed_suite_count: number;
            /** Expected Games */
            expected_games: number;
            /** Completed Games */
            completed_games: number;
            /**
             * Score Orientation
             * @constant
             */
            score_orientation: "subject";
            /** Is Complete */
            is_complete: boolean;
            /** Aggregate Is Partial */
            aggregate_is_partial: boolean;
            aggregate: components["schemas"]["Scores"] | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /**
             * Heartbeat At
             * Format: date-time
             */
            heartbeat_at: string;
            diagnostics: components["schemas"]["Diagnostics"];
        };
        /** Experiment */
        Experiment: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Game Config */
            game_config: {
                [key: string]: unknown;
            };
            /** Game Config Fingerprint */
            game_config_fingerprint: string;
            /** Current Champion Assignment Id */
            current_champion_assignment_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            counts: components["schemas"]["ExperimentCounts"];
            current_champion: components["schemas"]["CurrentChampion"] | null;
        };
        /** ExperimentContext */
        ExperimentContext: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Game Config */
            game_config: {
                [key: string]: unknown;
            };
            /** Game Config Fingerprint */
            game_config_fingerprint: string;
            /** Current Champion Assignment Id */
            current_champion_assignment_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ExperimentCounts */
        ExperimentCounts: {
            /** Attempts */
            attempts: number;
            /** Checkpoints */
            checkpoints: number;
            /** Evaluation Batches */
            evaluation_batches: number;
        };
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unavailable";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /**
             * Schema
             * @enum {string}
             */
            schema: "compatible" | "incompatible" | "unknown";
            /** Current Revision */
            current_revision: string | null;
            /** Head Revision */
            head_revision: string | null;
        };
        /** Lineage */
        Lineage: {
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
            experiment: components["schemas"]["ExperimentContext"];
            counts: components["schemas"]["ExperimentCounts"];
            current_champion: components["schemas"]["CurrentChampion"] | null;
            /** Root Checkpoint Id */
            root_checkpoint_id: string | null;
            /** Episode Min */
            episode_min: number | null;
            /** Episode Max */
            episode_max: number | null;
            attempts: components["schemas"]["Page_AttemptSummary_"];
            checkpoints: components["schemas"]["Page_CheckpointNode_"];
            /** Boundary Checkpoints */
            boundary_checkpoints: components["schemas"]["CheckpointNode"][];
            /** Edges */
            edges: components["schemas"]["AncestryEdge"][];
            /** Champion History */
            champion_history: components["schemas"]["ChampionAssignment"][];
            /** Truncated */
            truncated: boolean;
        };
        /** MatchStats */
        MatchStats: {
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Draws */
            draws: number;
            /** Losses */
            losses: number;
            /** Score Difference Sum */
            score_difference_sum: number;
            /** Match Score Numerator */
            match_score_numerator: number;
            /** Match Score Denominator */
            match_score_denominator: number;
            /** Match Score */
            match_score: number | null;
            /** Mean Score Difference */
            mean_score_difference: number | null;
        };
        /** MetricSample */
        MetricSample: {
            /** Attempt Id */
            attempt_id: string;
            /** Sample Sequence */
            sample_sequence: number;
            /** Episode */
            episode: number;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Metrics */
        Metrics: {
            /** Attempt Id */
            attempt_id: string;
            /** Items */
            items: components["schemas"]["MetricSample"][];
            /** Total Samples */
            total_samples: number;
            /** Omitted Samples */
            omitted_samples: number;
            /** Stride */
            stride: number;
            /**
             * Method
             * @constant
             */
            method: "uniform_samples";
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
            /** Episode Min */
            episode_min: number | null;
            /** Episode Max */
            episode_max: number | null;
        };
        /** ModelArchitecture */
        ModelArchitecture: {
            /** Channels */
            channels: number;
            /** Blocks */
            blocks: number;
            /**
             * Kind
             * @default dqn
             */
            kind: string;
        };
        /** Page[AttemptSummary] */
        Page_AttemptSummary_: {
            /** Items */
            items: components["schemas"]["AttemptSummary"][];
            /** Total */
            total: number;
            /** Remaining */
            remaining: number;
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
        };
        /** Page[CheckpointNode] */
        Page_CheckpointNode_: {
            /** Items */
            items: components["schemas"]["CheckpointNode"][];
            /** Total */
            total: number;
            /** Remaining */
            remaining: number;
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
        };
        /** Page[CheckpointSummary] */
        Page_CheckpointSummary_: {
            /** Items */
            items: components["schemas"]["CheckpointSummary"][];
            /** Total */
            total: number;
            /** Remaining */
            remaining: number;
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
        };
        /** Page[Decision] */
        Page_Decision_: {
            /** Items */
            items: components["schemas"]["Decision"][];
            /** Total */
            total: number;
            /** Remaining */
            remaining: number;
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
        };
        /** Page[EvaluationSuite] */
        Page_EvaluationSuite_: {
            /** Items */
            items: components["schemas"]["EvaluationSuite"][];
            /** Total */
            total: number;
            /** Remaining */
            remaining: number;
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
        };
        /** Page[EvaluationSummary] */
        Page_EvaluationSummary_: {
            /** Items */
            items: components["schemas"]["EvaluationSummary"][];
            /** Total */
            total: number;
            /** Remaining */
            remaining: number;
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
        };
        /** Page[Experiment] */
        Page_Experiment_: {
            /** Items */
            items: components["schemas"]["Experiment"][];
            /** Total */
            total: number;
            /** Remaining */
            remaining: number;
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
        };
        /** Scores */
        Scores: {
            overall: components["schemas"]["MatchStats"];
            as_player_0: components["schemas"]["MatchStats"];
            as_player_1: components["schemas"]["MatchStats"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    experiments_api_v1_experiments_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Experiment_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    lineage_api_v1_experiments__id__lineage_get: {
        parameters: {
            query?: {
                root_checkpoint_id?: string | null;
                episode_min?: number | null;
                episode_max?: number | null;
                attempt_limit?: number;
                attempt_cursor?: string | null;
                checkpoint_limit?: number;
                checkpoint_cursor?: string | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lineage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    attempts_api_v1_attempts_get: {
        parameters: {
            query?: {
                experiment_id?: string | null;
                starting_checkpoint_id?: string | null;
                status?: ("planned" | "running" | "completed" | "interrupted" | "failed" | "abandoned" | "cancelled") | null;
                phase?: ("training" | "screening" | "challenging" | "finished") | null;
                outcome?: string | null;
                created_after?: string | null;
                created_before?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AttemptSummary_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    attempt_api_v1_attempts__id__get: {
        parameters: {
            query?: {
                checkpoint_limit?: number;
                checkpoint_cursor?: string | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptDetail"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    metrics_api_v1_attempts__id__metrics_get: {
        parameters: {
            query?: {
                episode_min?: number | null;
                episode_max?: number | null;
                max_points?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    checkpoint_api_v1_checkpoints__id__get: {
        parameters: {
            query?: {
                evaluation_limit?: number;
                evaluation_cursor?: string | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointDetail"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    download_api_v1_checkpoints__id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Unchanged checkpoint */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    evaluation_api_v1_evaluations__id__get: {
        parameters: {
            query?: {
                suite_limit?: number;
                suite_cursor?: string | null;
                decision_limit?: number;
                decision_cursor?: string | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationDetail"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
